name: Build Windows 32-Bit
on: [push]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Code auschecken
        uses: actions/checkout@v4

      - name: Rust und 32-Bit-Target installieren
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: i686-pc-windows-msvc

      # Rust-Cache mit Pfad zum Tauri-Ordner
      - name: Rust Cache einrichten
        uses: swatinem/rust-cache@v2
        with:
          key: i686-pc-windows-msvc
          workspaces: "src-tauri -> target"

      # Schnelle Installation der Tauri CLI
      - name: cargo-binstall & tauri-cli installieren
        shell: powershell
        run: |
          Set-ExecutionPolicy Unclassified -Scope Process -Force
          iex (iwr -useb https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.ps1)
          cargo binstall tauri-cli --version "^2.0.0" -y

      - name: Anwendung nativ kompilieren
        run: cargo tauri build --target i686-pc-windows-msvc --no-bundle
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Fertiges ZIP-Paket bereitstellen
        uses: actions/upload-artifact@v4
        with:
          name: MetadatenEditor-Win32
          path: src-tauri/target/i686-pc-windows-msvc/release/